# No Augmentation Settings
no_augmentation:
  hyperparameters:
    batch_size: 32 # 보통은 2의 거듭제곱으로 둡니다
    learning_rate: 0.05 # 보통은 10의 거듭제곱으로 둡니다
    num_epochs: 20 # 보통은 10의 배수로 둡니다

# Augmentation Settings
augmentation:
  hyperparameters:
    batch_size: 32
    learning_rate: 0.001
    num_epochs: 20